# Generated by Django 5.1.3 on 2024-12-01 23:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='prefered_colors',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='prefered_location',
        ),
        migrations.RemoveField(
            model_name='users',
            name='location',
        ),
        migrations.AddField(
            model_name='garmenttags',
            name='tag_picture',
            field=models.ImageField(null=True, upload_to='media/tag_picture/'),
        ),
        migrations.AddField(
            model_name='users',
            name='liter_counter',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('En proceso', 'En proceso'), ('Entregado', 'Entregado'), ('Imposible entregar', 'Imposible entregar'), ('Cancelado', 'Cancelado')], default='En proceso', max_length=45),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='suggested_location',
            field=models.CharField(default='Patio Central PUCE', max_length=255),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='prefered_free_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=300), size=None),
        ),
        migrations.DeleteModel(
            name='Scores',
        ),
    ]
